package org.concourplus.service.mapper;

public enum EnumMapper {
	MAPPING_BASIC_USER,
	MAPPING_USER_AUTHENTICATION,
	MAPPING_USER_REGISTER,
	MAPPING_USER_EDIT,
	MAPPING_STATUS_ALL,
	MAPPING_PROFILE_ALL
}
